import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TestProvider from "@/provider/TestProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
        'base:app_id': '696a1df28aabd019b25f5292',
        'fc:miniapp': JSON.stringify({
            version: 'next',
            imageUrl: 'https://your-app.com/embed-image',
            button: {
                title: `Launch Your App Name`,
                action: {
                    type: 'launch_miniapp',
                    name: 'Your App Name',
                    url: 'https://your-app.com',
                    splashImageUrl: 'https://your-app.com/splash-image',
                    splashBackgroundColor: '#000000',
                },
            },
        }),
    },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <TestProvider>
              {children}
          </TestProvider>
      </body>
    </html>
  );
}
